language: rust
branches:
  only:
  - gh-pages
  - /.*/
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - cargo --version
  - rustc --version
script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" = stable ]]; then
      cargo tarpaulin --no-count --skip-clean --out Xml &&
      bash <(curl -s https://codecov.io/bash)
    fi
  - |
    if [[ "$TRAVIS_RUST_VERSION" = nightly ]]; then
      cargo install --force rustfmt-nightly &&
      rustfmt --version &&
      find . -name '*.rs' | xargs rustfmt &&
      git diff --exit-code
    fi
